### ISSUE TITLE
How to create Cross-Platform Installers  with Github Actions ?

### ISSUE THREAD

**Issue by ghost** [Srijan-Sengupta/Paint-India-Gradle-Desktop#3]
I asked this because I did't know anything about Github Actions.

Can you give a tutorial to create  installer for different platforms ?

**Comment by Srijan-Sengupta** [comment]
Obviously I can. Follow these steps thoroughly :
1. Learn [YAML](https://www.tutorialspoint.com/yaml/index.htm).
2. Here is [Github Actions Documentations](https://docs.github.com/en/free-pro-team@latest/actions) **Read these carefully...**
3. Try reading [this](https://docs.github.com/en/free-pro-team@latest/actions/quickstart) and [this](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-gradle).
4. Here are some implementations of Github Actions:
 - [My Implementation in Paint-India-Desktop](https://github.com/Srijan-Sengupta/Paint-India-Gradle-Desktop/blob/master/.github/workflows/multiplatform.yml)
 - [badass-runtime-javafx-example](https://github.com/beryx-gist/badass-runtime-example-javafx/blob/master/.github/workflows/gradle.yml)

**Comment by ghost** [comment]
![buildfailed](https://user-images.githubusercontent.com/67687893/99765733-9b8e1200-2af7-11eb-8a36-2211acc200c0.PNG)


why you marked like this ?

was this build  failed?

**Comment by Srijan-Sengupta** [comment]
Hey @parasuraam sorry for my inactivity! The answers to this is **no.** Actually this badge Always gives the status of the project build. I was trying Azure Pipelines which was failing not Github Actions. For now, I have disabled Github Actions because I had Overused it which led to cost me money.

**Comment by ghost** [comment]
![pic 1](https://user-images.githubusercontent.com/67687893/99936602-6a158080-2d5b-11eb-9730-e703e11e9b08.PNG)


I used the Github Action to create  jpackage .

but , it only created the jpackage for windows.

build failed for mac and linux.

why it failed for linux and mac?

My project :  https://github.com/parasuraam/new/actions/runs/378383207

How can I solve this ?

**Comment by Srijan-Sengupta** [comment]
It seems like you have overlooked these lines which **Grants Permission to gradle wrapper to execute** in my workflow file. Here are those lines : https://github.com/Srijan-Sengupta/Paint-India-Gradle-Desktop/actions/runs/378270087/workflow#L23 
and this : https://github.com/Srijan-Sengupta/Paint-India-Gradle-Desktop/actions/runs/378270087/workflow#L24

**Comment by ghost** [comment]
gradle.yml 

https://github.com/parasuraam/new/blob/main/.github/workflows/gradle.yml

I want to create jpackage for windows, linux and mac.

but , I am confused. 

Can you explain in detail ?

**Comment by ghost** [comment]
I tried for 3 hours .
but , all failed.
 I want to create jpackage for linux and mac.

How can I do this ?

**Comment by Srijan-Sengupta** [comment]
I am sure neither you have gone through those tutorials nor the examples.
Doesn't matter.. here is the code:
```yaml
name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '14.0.2' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Upload DMG as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
    - name: Upload EXE as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
    - name: Upload DEB as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
    - name: Upload RPM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
```
